### ISSUE TITLE
[EPIC] Refactor rest-client

### ISSUE THREAD

**Issue by pastahito** [Linkurious/linkurious-rest-client#106]
EPIC Checklist:
- [x] Level 1 specs
  - backend
    - [x] issues created (by Back Lead)
    - [x] story points added (by Back Lead)
  - frontend 
    - [x] issues created (by Front Lead)
    - [ ] story points added (by Front Lead)
- [x] Schedule
  - [x] backend schedule added to teamweek (by Back Lead and PO)
  - [x] frontend schedule added to teamweek (by Front Lead and PO)
  - [ ] schedule validated (by CTO)
  - [x] epic validation date added to teamweek (by PO)
- [x] Tech specs: backend
  - [x] written (by Back Lead)
  - [x] developed rest client (by Back Lead)
  - [x] reviewed (by Front Lead)
  - [ ] reviewed (by CTO)
- [ ] Tech specs: frontend
  - [ ] components specs written (by Front Lead)
  - [ ] components specs reviewed (by PO) 
  - [ ] tech specs written (by Front Lead)
  - [ ] tech specs reviewed (by CTO) 
- [ ] Development
  - [x] shared (back) done (by Back Lead)
  - [ ] shared (front) done (by Front Lead)
  - [x] backend done (by Back Lead)
  - [ ] frontend done (by Front Lead)
- [ ] Validation
  - [ ] OK (by Product)
  - [x] tested with scenarios (by PO)

**Comment by thibaultlink** [comment]
Epic completed. Closing.
